### PR TITLE
minification of images

### PR DESCRIPTION
**Pull request by juliocarneiro**
💃

### CODE REVIEW

**Comment by ajiteshr7** [comment]
Images are oversized.It would be better if you can resize those images.
Also do not modify fonts.

**Comment by juliocarneiro** [comment]
Okay, this is work for a designer then :D you can close the PR

**Comment by ajiteshr7** [comment]
I will merge your PR, if you can leave fonts from your PR.

**Review by ajiteshr7 — CHANGES_REQUESTED** [review]
Do not modify fonts.

**Comment by juliocarneiro** [comment]
I did not minify the fonts, they were just not in my branch and were added

**Comment by ajiteshr7** [comment]
Ok, just modify your commit so that fonts are not deleted

**Pull request closed without merging**
